### ISSUE TITLE
load_user_setup.sh isnt executed at container creation

### ISSUE THREAD

**Issue by iNoSec2** [ThePorgs/Exegol-images#126]
Hello,
Thank you for this awesome project!
All is in the title, i have written a script i copy/paste in load_user_setup.sh with my-resources feature activated and it isnt executed during the docker creation. All others setup are executed like the additionnal packages, my vim config, the bin i imported but not the load_user_setup.sh script.

The log file doesnt mention any errors nor any mention of that script.

Thank in advance

**Comment by iNoSec2** [comment]
no ideas guys?

**Comment by iNoSec2** [comment]
So the` load_user_setup.sh` isnt loaded when we create the container the first time by using the `exegol start mycontainer full` i must stop it with `exegol stop mycontainer` and restart it again with `exegol start mycontainer` and at this step it is working, that's weird since all the others setup like the `bin` and `setup` stuff are directly applied at the container creation. Finally this setting lost all his interest since it is better to run my script myself after i create the container than exiting, closing it, restart it.
I will open an other issue for the `--vpn` options at the container creation who need the same mechanism which is exiting,stop the container and start it again to take the VPN config to be applied.

**Comment by Dramelac** [comment]
Hello @iNoSec2,

Thank you for your interest in the project.

Concerning your problem I just think it's a question of time. The launching of the different customization takes time (especially the apt update part etc. which depends on the speed of your internet access)

The restart of your container just allows you to "kill" the customization process. When restarting the container, the customization process does not restart again since it has already been launched once.

You can use `ps -faux` to see the different processes in progress and see which script / command is running. You can also monitor live the log file with `tail -f var/log/exegol/load_setups.log` to follow the evolution of the installation.

Let me know if you still have some problem with the system!
