### ISSUE TITLE
[BUG] renameMachine.py disapear

### ISSUE THREAD

**Issue by Syzik** [ThePorgs/Exegol-images#374]
### Describe the bug

![image](https://github.com/user-attachments/assets/2195e338-ed2b-48a3-98c1-77885f32f706)
![image](https://github.com/user-attachments/assets/735cfbe8-ed9f-46c8-9bed-c763eab030b6)

**Comment by p0dalirius** [comment]
![image](https://github.com/user-attachments/assets/8cbb1397-03f7-4a79-ada0-eca6a66eaa48)

**Comment by ShutdownRepo** [comment]
Thank you for raising this issue (and for the amazing meme 😂 )
Indeed, ThePorgs' fork was started all over again since it was getting impossible to merge any pull requests (since the code was too different between the fork and upstream). We hadn't merged the corresponding PR https://github.com/fortra/impacket/pull/1224. I merged it now. 
Please feel free to test again on the next `nightly` image (or by updating your Impacket instance locally with `pipx install --force --system-site-packages git+https://github.com/ThePorgs/impacket`), and re-open if the issue persists in the next image(s)
